(() => {
  'use strict';

  const BUILD = Object.freeze({version:'0.9.0',id:'living-world-reboot',saveKey:'briar-glen-reboot-v1'});
  const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
  const UI={clock:document.getElementById('clock'),coins:document.getElementById('coins'),hp:document.getElementById('hp'),energy:document.getElementById('energy'),standing:document.getElementById('standing'),knownFor:document.getElementById('known-for'),skills:document.getElementById('skills'),inventory:document.getElementById('inventory'),packWeight:document.getElementById('pack-weight'),nearby:document.getElementById('nearby'),nearbyType:document.getElementById('nearby-type'),log:document.getElementById('log'),toast:document.getElementById('toast'),worldLine:document.getElementById('world-line')};
  const TAU=Math.PI*2,clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
  const rand=(a,b)=>a+Math.random()*(b-a);

  const itemDefs=Object.freeze({
    briarleaf:{name:'Briarleaf',weight:.2,base:4,kind:'herb',color:'#8fcf72'},
    mooncap:{name:'Mooncap',weight:.2,base:9,kind:'herb',color:'#b9a3d9'},
    iron:{name:'Iron Ore',weight:1.2,base:12,kind:'ore',color:'#9fa8ad'},
    wood:{name:'Ashwood',weight:.8,base:7,kind:'wood',color:'#aa8457'},
    hide:{name:'Wolf Hide',weight:.7,base:15,kind:'hide',color:'#b99878'},
    bread:{name:'Brown Bread',weight:.3,base:6,kind:'food',color:'#d7ad69'},
    tonic:{name:'Field Tonic',weight:.2,base:22,kind:'medicine',color:'#7fcaad'},
    pick:{name:'Iron Pick',weight:2,base:50,kind:'tool',color:'#b9c1c4'},
    hammer:{name:'Forge Hammer',weight:2.2,base:64,kind:'tool',color:'#aeb7bc'},
    shears:{name:'Herbal Shears',weight:1.1,base:46,kind:'tool',color:'#b7c5bd'},
    blade:{name:'Warden Blade',weight:2.4,base:80,kind:'weapon',color:'#d2d6d7'},
  });

  const recipes=Object.freeze({
    tonic:{skill:'herbcraft',level:1,input:{briarleaf:2,mooncap:1},output:'tonic'},
    pick:{skill:'smithing',level:1,input:{iron:3,wood:1},output:'pick'},
    blade:{skill:'smithing',level:2,input:{iron:4,wood:1,hide:1},output:'blade'},
  });

  const skillDefs=Object.freeze({
    fieldcraft:{name:'Fieldcraft',key:'1',active:'Survey',desc:'Reveal quality and find safer routes for nearby work.'},
    smithing:{name:'Smithing',key:'2',active:'Mend',desc:'Repair your gear or service a nearby person’s damaged gear.'},
    guard:{name:'Guard',key:'3',active:'Brace',desc:'Block the next hit and counter.'},
    rapport:{name:'Rapport',key:'4',active:'Connect',desc:'Read a need and broker a real promise between people.'},
    herbcraft:{name:'Herbcraft',key:null,active:null,desc:'Brew useful medicine from plants.'},
  });

  const world={w:1800,h:1200,minute:8*60,day:1,weather:'clear',weatherTimer:220,events:[],resources:[],enemies:[],drops:[],townNeeds:{food:0,medicine:0,metal:0},serial:1};
  const camera={x:0,y:0};
  const player={x:900,y:600,r:12,speed:170,hp:100,maxHp:100,energy:100,maxEnergy:100,coins:24,attackCd:0,attackArc:0,guarded:false,surveyUntil:0,readNeedUntil:0,equippedTool:null,equippedWeapon:null,knownFor:'nothing yet',standing:'Unknown',inventory:{},skills:{}};
  for(const key of Object.keys(skillDefs))player.skills[key]={xp:0,level:1};

  const zones=[
    {id:'village',name:'Briar Glen',x:650,y:390,w:500,h:420,color:'#596c4e'},
    {id:'forest',name:'Greenwood',x:1160,y:220,w:560,h:470,color:'#354b34'},
    {id:'quarry',name:'Old Quarry',x:80,y:180,w:520,h:470,color:'#51504c'},
    {id:'marsh',name:'Moss Fen',x:1020,y:760,w:640,h:360,color:'#3a5550'},
    {id:'meadow',name:'South Meadow',x:160,y:720,w:720,h:390,color:'#60784f'},
  ];

  const buildings=[
    {id:'forge',name:'Alden’s Forge',x:760,y:500,w:105,h:80,color:'#714a36'},
    {id:'apothecary',name:'Mira’s Garden',x:930,y:465,w:110,h:75,color:'#4e704a'},
    {id:'market',name:'Rowan’s Stall',x:820,y:650,w:120,h:62,color:'#7b6741'},
    {id:'hall',name:'Warden Hall',x:990,y:625,w:110,h:78,color:'#5d615f'},
  ];

  const npcTemplates=[
    {id:'alden',name:'Alden',role:'smith',home:{x:812,y:545},work:{x:812,y:545},color:'#c48b63',needBias:{iron:1.8,wood:1.1,hammer:2.4,bread:1}},
    {id:'mira',name:'Mira',role:'herbalist',home:{x:985,y:520},work:{x:985,y:520},color:'#8fb783',needBias:{briarleaf:1.4,mooncap:1.8,shears:2.4,bread:1}},
    {id:'rowan',name:'Rowan',role:'trader',home:{x:870,y:680},work:{x:870,y:680},color:'#d1b26c',needBias:{bread:1.7,tonic:1,wood:.8}},
    {id:'tamsin',name:'Tamsin',role:'warden',home:{x:1030,y:670},work:{x:1110,y:570},color:'#7aa2c3',needBias:{tonic:1.5,hide:1.3,pick:.7,blade:.8,bread:1}},
  ];

  const productionRecipes=Object.freeze({
    herbalist:Object.freeze({output:'tonic',req:Object.freeze({briarleaf:2,mooncap:1})}),
    smith:Object.freeze({output:'pick',req:Object.freeze({iron:3,wood:1})}),
  });
  const professionTools=Object.freeze({smith:'hammer',herbalist:'shears',warden:'blade'});

  let npcs=[];
  function newNPC(t){const stock={bread:1},stockMeta={};if(t.role==='warden'){stock.blade=1;stockMeta.blade={quality:1.2,durability:72,maxDurability:80,provenance:{maker:'Alden',madeDay:1,source:'Warden issue',materialQuality:1.1,skillLevel:2,repairs:0,history:['Issued by Alden before Day 1.']}};}if(t.role==='smith'){stock.hammer=1;stockMeta.hammer={quality:1.35,durability:78,maxDurability:90,provenance:{maker:'Alden',madeDay:1,source:'Alden’s Forge',materialQuality:1.3,skillLevel:3,repairs:0,history:['Alden forged this hammer before Day 1.']}};}if(t.role==='herbalist'){stock.shears=1;stockMeta.shears={quality:1.15,durability:66,maxDurability:75,provenance:{maker:'Alden',madeDay:1,source:'Mira’s working kit',materialQuality:1.1,skillLevel:2,repairs:0,history:['Alden made these shears for Mira before Day 1.']}};}return{...t,x:t.home.x,y:t.home.y,r:11,energy:80,hunger:20,mood:60,trust:0,goal:'idle',goalText:'Taking stock',target:{...t.home},memory:[],relations:{},stock,stockMeta,request:null,think:0,productionCooldown:0,exchangeCooldown:0,seekSource:null,productionPlan:null,blockedByDanger:null,avoidEnemyId:null,routeOverride:null,socialCommitment:null,brokeredNeed:null,trades:0,lastPlayerHelp:0};}

  function qualityLabel(q){return q>=2.6?'fine':q>=1.7?'good':'plain';}
  function isArtifact(id){const kind=itemDefs[id]?.kind;return kind==='tool'||kind==='weapon';}
  function itemCount(id){return player.inventory[id]?.qty||0;}
  function copy(value){return value==null?value:JSON.parse(JSON.stringify(value));}
  function artifactProvenance(id,quality,maker='Unknown',source='Found'){return{maker,madeDay:world.day,source,materialQuality:quality,skillLevel:0,repairs:0,history:[`Acquired on Day ${world.day}.`]};}
  function normalizeArtifactSlot(id,slot){if(!slot||!isArtifact(id))return slot;slot.qty=1;slot.qualitySum=Number.isFinite(slot.qualitySum)?slot.qualitySum:1;slot.maxDurability=Number.isFinite(slot.maxDurability)?slot.maxDurability:100;slot.durability=clamp(Number.isFinite(slot.durability)?slot.durability:slot.maxDurability,0,slot.maxDurability);slot.provenance=slot.provenance&&typeof slot.provenance==='object'?slot.provenance:artifactProvenance(id,slot.qualitySum,'Unknown','Legacy item');slot.provenance.repairs=Number(slot.provenance.repairs||0);slot.provenance.history=Array.isArray(slot.provenance.history)?slot.provenance.history:[];return slot;}
  function artifactSnapshot(id){const slot=normalizeArtifactSlot(id,player.inventory[id]);if(!slot)return null;return{quality:avgQuality(id),durability:slot.durability,maxDurability:slot.maxDurability,provenance:copy(slot.provenance)};}
  function npcArtifactState(n,id){if(!n||!isArtifact(id)||(n.stock?.[id]||0)<1)return null;n.stockMeta??={};let meta=n.stockMeta[id];if(!meta){meta={quality:1,durability:70,maxDurability:80,provenance:{maker:'Unknown',madeDay:world.day,source:`${n.name}'s gear`,materialQuality:1,skillLevel:0,repairs:0,history:[`Recorded in ${n.name}'s possession on Day ${world.day}.`]}};n.stockMeta[id]=meta;}meta.quality=Number.isFinite(meta.quality)?meta.quality:1;meta.maxDurability=Number.isFinite(meta.maxDurability)?meta.maxDurability:80;meta.durability=clamp(Number.isFinite(meta.durability)?meta.durability:meta.maxDurability,0,meta.maxDurability);meta.provenance=meta.provenance&&typeof meta.provenance==='object'?meta.provenance:{maker:'Unknown',madeDay:world.day,source:`${n.name}'s gear`,materialQuality:meta.quality,skillLevel:0,repairs:0,history:[]};meta.provenance.history=Array.isArray(meta.provenance.history)?meta.provenance.history:[];return meta;}
  function npcArtifactReady(n,id){const meta=npcArtifactState(n,id);return !!meta&&meta.durability>0;}
  function npcArtifactSnapshot(n,id){const meta=npcArtifactState(n,id);return meta?copy(meta):null;}
  function damagedArtifactForNpc(n){if(!n)return null;const found=[];for(const [id,qty] of Object.entries(n.stock||{})){if(!isArtifact(id)||qty<1)continue;const meta=npcArtifactState(n,id),ratio=meta?.maxDurability?meta.durability/meta.maxDurability:0;if(meta&&ratio<=.65)found.push({npc:n,id,meta,ratio});}found.sort((a,b)=>a.ratio-b.ratio);return found[0]||null;}
  function nearbyDamagedNpcArtifact(range=110){return npcs.map(n=>damagedArtifactForNpc(n)).filter(Boolean).filter(x=>dist(player,x.npc)<=range).sort((a,b)=>(a.ratio-b.ratio)||(dist(player,a.npc)-dist(player,b.npc)))[0]||null;}
  function serviceNpcArtifact(service,skill){if(!service||itemCount('iron')<1)return false;const {npc:n,id,meta}=service,before=meta.durability;removeItem('iron',1);const wear=Math.max(0,3-skill.level);meta.maxDurability=Math.max(45,meta.maxDurability-wear);meta.durability=Math.min(meta.maxDurability,meta.durability+30+skill.level*5);meta.provenance.repairs=Number(meta.provenance.repairs||0)+1;meta.provenance.history.push(`Serviced by You for ${n.name} on Day ${world.day} with Smithing ${skill.level}.`);if(meta.provenance.history.length>8)meta.provenance.history.shift();const restored=Math.max(0,meta.durability-before),commission=Math.max(5,Math.round(itemDefs[id].base*(.06+skill.level*.02)));player.coins+=commission;n.trust=clamp(n.trust+.35+skill.level*.08,0,10);memory(n,`You serviced my ${itemDefs[id].name}; I can rely on it again.`);n.request=requestFor(n);n.seekSource=null;n.productionPlan=null;n.goal='idle';n.target={...n.work};n.think=0;skillXp('smithing',8);deriveIdentity();save();log(`${n.name} paid ${commission}c after you restored ${itemDefs[id].name}.`,'npc');toast(`${n.name}'s ${itemDefs[id].name} restored +${Math.round(restored)}`);return true;}
  function addItem(id,qty=1,quality=1,artifact=null){if(!itemDefs[id])return false;if(isArtifact(id)){if(itemCount(id)>0)return false;const provenance=copy(artifact?.provenance)||artifactProvenance(id,quality,artifact?.maker||'Unknown',artifact?.source||'Found');const maxDurability=clamp(Number(artifact?.maxDurability??100),55,100);player.inventory[id]={qty:1,qualitySum:quality,durability:clamp(Number(artifact?.durability??maxDurability),0,maxDurability),maxDurability,provenance};log(`Picked up ${itemDefs[id].name} (${qualityLabel(quality)}; ${provenance.maker}).`,'world');return true;}const slot=player.inventory[id]||(player.inventory[id]={qty:0,qualitySum:0,durability:null});slot.qty+=qty;slot.qualitySum+=quality*qty;log(`Picked up ${qty} ${itemDefs[id].name}${quality>1.05?` (${qualityLabel(quality)})`:''}.`,'world');return true;}
  function removeItem(id,qty=1){const slot=player.inventory[id];if(!slot||slot.qty<qty)return false;if(isArtifact(id)){delete player.inventory[id];if(player.equippedTool===id)player.equippedTool=null;if(player.equippedWeapon===id)player.equippedWeapon=null;return true;}const avg=slot.qualitySum/slot.qty;slot.qty-=qty;slot.qualitySum=Math.max(0,slot.qualitySum-avg*qty);if(slot.qty<=0)delete player.inventory[id];return true;}
  function avgQuality(id){const s=player.inventory[id];return s&&s.qty?s.qualitySum/s.qty:1;}
  function hasItems(req){return Object.entries(req).every(([id,q])=>itemCount(id)>=q);}
  function consume(req){if(!hasItems(req))return false;for(const [id,q] of Object.entries(req))removeItem(id,q);return true;}
  function inventoryWeight(){return Object.entries(player.inventory).reduce((sum,[id,s])=>sum+(itemDefs[id]?.weight||0)*s.qty,0);}

  function skillXp(id,amount){const s=player.skills[id];if(!s)return;const before=s.level;s.xp+=amount;while(s.xp>=s.level*40&&s.level<5){s.xp-=s.level*40;s.level++;}if(s.level>before){toast(`${skillDefs[id].name} reached ${s.level}`);log(`${skillDefs[id].name} improved. New actions may be stronger.`,'world');}}
  function useSkill(id){const s=player.skills[id];if(!s)return false;
    if(id==='fieldcraft'){if(player.energy<8){toast('Too tired to survey');return false;}player.surveyUntil=performance.now()+7000;player.energy-=8;const rerouted=rerouteBlockedWork();skillXp(id,rerouted?7:3);toast(rerouted?`Survey: found a safer ${itemDefs[rerouted.itemId].name} route for ${rerouted.npcName}`:'Survey: quality and resources revealed');return true;}
    if(id==='smithing'){const service=nearbyDamagedNpcArtifact();if(service){if(itemCount('iron')<1){toast(`Servicing ${service.npc.name} needs 1 Iron Ore`);return false;}return serviceNpcArtifact(service,s);}const target=player.equippedWeapon||player.equippedTool;if(!target||!player.inventory[target]){toast('Equip damaged gear or stand near someone who needs service');return false;}if(itemCount('iron')<1){toast('Mend needs 1 Iron Ore');return false;}const slot=normalizeArtifactSlot(target,player.inventory[target]);removeItem('iron',1);const wear=Math.max(0,3-s.level);slot.maxDurability=Math.max(55,slot.maxDurability-wear);slot.durability=Math.min(slot.maxDurability,slot.durability+35+s.level*4);slot.provenance.repairs+=1;slot.provenance.history.push(`Mended by You on Day ${world.day} with Smithing ${s.level}.`);if(slot.provenance.history.length>8)slot.provenance.history.shift();skillXp(id,4);save();toast(`${itemDefs[target].name} mended to ${Math.round(slot.durability)}/${Math.round(slot.maxDurability)}`);return true;}
    if(id==='guard'){if(player.energy<10){toast('Too tired to brace');return false;}player.energy-=10;player.guarded=true;skillXp(id,2);toast('Braced: next hit will be blocked');return true;}
    if(id==='rapport'){const n=nearestNPC(110);if(!n){toast('No one close enough to connect');return false;}player.readNeedUntil=performance.now()+8000;memory(n,`You paid attention when ${n.goalText.toLowerCase()}.`);const brokered=brokerNeed(n);skillXp(id,brokered?7:3);toast(brokered?`${brokered.supplierName} agreed to bring ${itemDefs[brokered.itemId].name} to ${n.name}`:`${n.name}: ${npcNeedText(n)}`);return true;}
    return false;
  }

  function log(text,type='world'){world.events.push({id:world.serial++,text,type,day:world.day,minute:world.minute});if(world.events.length>70)world.events.shift();renderLog();}
  let toastTimer=0;function toast(text){UI.toast.textContent=text;UI.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>UI.toast.classList.remove('show'),1500);}

  function zoneAt(x,y){return zones.find(z=>x>=z.x&&x<=z.x+z.w&&y>=z.y&&y<=z.y+z.h)||null;}
  function spawnResource(type,x,y,quality=1){world.resources.push({id:`r${world.serial++}`,type,x,y,r:type==='iron'?12:9,quality,respawn:0,available:true});}
  function seedResources(){world.resources.length=0;
    for(let i=0;i<16;i++)spawnResource('briarleaf',rand(180,830),rand(760,1060),rand(.9,1.8));
    for(let i=0;i<10;i++)spawnResource('mooncap',rand(1220,1660),rand(780,1080),rand(1.1,2.4));
    for(let i=0;i<14;i++)spawnResource('iron',rand(140,540),rand(250,610),rand(.8,2.5));
    for(let i=0;i<14;i++)spawnResource('wood',rand(1210,1680),rand(270,640),rand(.8,2.2));
  }
  function spawnWolf(x,y){world.enemies.push({id:`w${world.serial++}`,type:'wolf',x,y,r:12,hp:36,maxHp:36,attackCd:0,wander:rand(0,10),dead:false});}
  function seedEnemies(){world.enemies.length=0;for(let i=0;i<6;i++)spawnWolf(rand(1240,1670),rand(300,650));for(let i=0;i<3;i++)spawnWolf(rand(350,800),rand(820,1040));}

  function reset(){world.minute=8*60;world.day=1;world.weather='clear';world.weatherTimer=220;world.events=[];world.serial=1;player.x=900;player.y=600;player.hp=100;player.energy=100;player.coins=24;player.inventory={};player.equippedTool=null;player.equippedWeapon=null;player.knownFor='nothing yet';player.standing='Unknown';for(const k of Object.keys(player.skills))player.skills[k]={xp:0,level:1};npcs=npcTemplates.map(newNPC);seedResources();seedEnemies();addItem('bread',2,1);log('A new day begins in Briar Glen. Everyone here has needs of their own.','world');save();}

  function memory(n,text){n.memory.push({day:world.day,text});if(n.memory.length>12)n.memory.shift();}
  function npcNeedScore(n,id){const raw=n.stock[id]||0,stock=isArtifact(id)&&raw>0&&!npcArtifactReady(n,id)?0:raw,bias=n.needBias[id]||0,target=isArtifact(id)?1:3;return bias*Math.max(0,target-stock)+(id==='bread'?n.hunger/35:0);}
  function topNeed(n){let best={id:'bread',score:0};for(const id of Object.keys(n.needBias)){const score=npcNeedScore(n,id);if(score>best.score)best={id,score};}return best;}
  function npcNeedText(n){const need=topNeed(n);return need.score>.6?`${itemDefs[need.id].name} matters most right now.`:'No urgent shortage.';}
  function requestFor(n){const need=topNeed(n);if(need.score<1.1)return null;const qty=isArtifact(need.id)?1:need.score>3?2:1;const reward=Math.round(itemDefs[need.id].base*qty*(1.35+need.score*.08));return{id:need.id,qty,reward,createdDay:world.day};}
  function pointSegmentDistance(p,a,b){const vx=b.x-a.x,vy=b.y-a.y,wx=p.x-a.x,wy=p.y-a.y,len=vx*vx+vy*vy;if(!len)return Math.hypot(wx,wy);const t=clamp((wx*vx+wy*vy)/len,0,1),px=a.x+t*vx,py=a.y+t*vy;return Math.hypot(p.x-px,p.y-py);}
  function dangerOnRoute(from,to,radius=95){let best=null,bd=radius;for(const e of world.enemies){if(e.dead)continue;const d=pointSegmentDistance(e,from,to);if(d<bd){best=e;bd=d;}}return best;}
  function fieldSpot(id,seeker=null,safeOnly=false){let nodes=world.resources.filter(r=>r.available&&r.type===id);if(safeOnly&&seeker)nodes=nodes.filter(r=>!dangerNear(r,125)&&!dangerOnRoute(seeker,r,95));if(nodes.length){nodes.sort((a,b)=>(seeker?dist(seeker,a):0)-(seeker?dist(seeker,b):0));return{x:nodes[0].x,y:nodes[0].y,id:nodes[0].id};}if(safeOnly)return null;return id==='iron'?{x:360,y:430}:id==='wood'?{x:1430,y:450}:id==='mooncap'?{x:1370,y:930}:id==='briarleaf'?{x:520,y:900}:null;}
  function supplierFor(seeker,id){const preferred=id==='bread'?'rowan':id==='tonic'?'mira':id==='pick'||id==='blade'?'alden':null;const candidates=npcs.filter(o=>o!==seeker&&(o.stock?.[id]||0)>0&&(!isArtifact(id)||npcArtifactReady(o,id))&&!o.socialCommitment);candidates.sort((a,b)=>((b.id===preferred)- (a.id===preferred))||((b.stock[id]||0)-(a.stock[id]||0)));return candidates[0]||null;}
  function brokerNeed(requester){const need=topNeed(requester);if(need.score<1.1||requester.brokeredNeed)return null;const supplier=supplierFor(requester,need.id);if(!supplier)return null;const commitment={requesterId:requester.id,itemId:need.id,createdDay:world.day,brokeredBy:'player'};supplier.socialCommitment=commitment;supplier.productionPlan=null;supplier.seekSource=null;supplier.goal='deliver';supplier.target={x:requester.x,y:requester.y};supplier.goalText=`Promised ${requester.name} ${itemDefs[need.id].name} because you connected us`;supplier.think=9;requester.brokeredNeed={supplierId:supplier.id,itemId:need.id,createdDay:world.day};requester.seekSource=null;requester.goal='await';requester.target={...requester.work};requester.goalText=`Waiting on ${supplier.name}'s promised ${itemDefs[need.id].name}`;requester.think=9;memory(requester,`You connected ${supplier.name} to my need for ${itemDefs[need.id].name}.`);memory(supplier,`You connected me to ${requester.name}'s need for ${itemDefs[need.id].name}.`);log(`You brokered a ${itemDefs[need.id].name} promise between ${supplier.name} and ${requester.name}.`,'npc');return{requesterId:requester.id,supplierId:supplier.id,supplierName:supplier.name,itemId:need.id};}
  function relation(a,b,delta){a.relations??={};a.relations[b.id]=clamp((a.relations[b.id]||0)+delta,-5,10);}
  function liveEnemy(id){return world.enemies.find(e=>e.id===id&&!e.dead)||null;}
  function dangerNear(point,radius=120){let best=null,bd=radius;for(const e of world.enemies){if(e.dead)continue;const d=Math.hypot(e.x-point.x,e.y-point.y);if(d<bd){best=e;bd=d;}}return best;}
  function activeDangerReport(){for(const reporter of npcs){const report=reporter.blockedByDanger;if(!report)continue;const enemy=liveEnemy(report.enemyId);if(enemy)return{reporter,enemy,report};reporter.blockedByDanger=null;}return null;}
  function rerouteBlockedWork(){const candidates=npcs.filter(n=>n.blockedByDanger&&dist(player,n)<220).sort((a,b)=>dist(player,a)-dist(player,b));const n=candidates[0];if(!n)return null;const report=n.blockedByDanger,enemy=liveEnemy(report.enemyId);if(!enemy){n.blockedByDanger=null;return null;}const safe=fieldSpot(report.itemId,n,true);if(!safe)return null;n.avoidEnemyId=enemy.id;n.blockedByDanger=null;n.seekSource=null;n.routeOverride={itemId:report.itemId,resourceId:safe.id,enemyId:enemy.id};n.goal='seek';n.target={x:safe.x,y:safe.y,id:safe.id};n.goalText=`Following your safer route to ${itemDefs[report.itemId].name}`;n.think=8;n.trust=clamp(n.trust+.3,0,10);memory(n,`You surveyed a safer route to ${itemDefs[report.itemId].name} instead of fighting through the wolf.`);log(`Your Fieldcraft gave ${n.name} a safer way around the wolf.`,'world');return{npcId:n.id,npcName:n.name,itemId:report.itemId,enemyId:enemy.id,resourceId:safe.id};}
  function productionDemand(n){const recipe=productionRecipes[n.role];if(!recipe)return 0;let demand=0;for(const other of npcs){if(other===n)continue;const need=topNeed(other);if(need.id===recipe.output)demand+=need.score;}return demand;}
  function productionNeed(n){const recipe=productionRecipes[n.role];if(!recipe)return null;const demand=productionDemand(n);if(demand<1||(n.stock[recipe.output]||0)>0)return null;const missing=Object.entries(recipe.req).map(([id,qty])=>({id,qty,have:n.stock[id]||0,short:Math.max(0,qty-(n.stock[id]||0))})).filter(x=>x.short>0).sort((a,b)=>(b.short/b.qty)-(a.short/a.qty))[0];return missing?{...missing,output:recipe.output,score:demand*1.25+1}:null;}
  function chooseNpcGoal(n){if(n.blockedByDanger&&!liveEnemy(n.blockedByDanger.enemyId))n.blockedByDanger=null;if(n.avoidEnemyId&&!liveEnemy(n.avoidEnemyId)){n.avoidEnemyId=null;n.routeOverride=null;}if(n.socialCommitment){const requester=npcs.find(x=>x.id===n.socialCommitment.requesterId);if(requester&&(n.stock?.[n.socialCommitment.itemId]||0)>0){n.productionPlan=null;n.seekSource=null;n.goal='deliver';n.target={x:requester.x,y:requester.y};n.goalText=`Delivering promised ${itemDefs[n.socialCommitment.itemId].name} to ${requester.name}`;n.request=requestFor(n);return;}n.socialCommitment=null;}if(n.brokeredNeed){const supplier=npcs.find(x=>x.id===n.brokeredNeed.supplierId);if(supplier?.socialCommitment?.requesterId===n.id){n.productionPlan=null;n.seekSource=null;n.goal='await';n.target={...n.work};n.goalText=`Waiting on ${supplier.name}'s promised ${itemDefs[n.brokeredNeed.itemId].name}`;n.request=requestFor(n);return;}n.brokeredNeed=null;}if(n.routeOverride){const node=world.resources.find(r=>r.id===n.routeOverride.resourceId&&r.available);if(node){n.seekSource=null;n.goal='seek';n.target={x:node.x,y:node.y,id:node.id};n.goalText=`Following your safer route to ${itemDefs[n.routeOverride.itemId].name}`;n.request=requestFor(n);return;}n.routeOverride=null;}const workToolId=professionTools[n.role],workDemand=productionDemand(n);if(workToolId&&n.role!=='warden'&&workDemand>1&&!npcArtifactReady(n,workToolId)){n.needBias[workToolId]=Math.max(n.needBias[workToolId]||0,7);n.productionPlan=null;n.seekSource=null;n.goal='gear';n.target={...n.work};n.goalText=`${itemDefs[workToolId].name} needs service; ${itemDefs[productionRecipes[n.role].output].name} work is stalled`;n.request=requestFor(n);return;}const dangerCall=n.role==='warden'?activeDangerReport():null;if(dangerCall){n.productionPlan=null;n.seekSource=null;if(!npcArtifactReady(n,'blade')){n.needBias.blade=Math.max(n.needBias.blade||0,6);const supplier=supplierFor(n,'blade');if(supplier){n.seekSource=supplier.id;n.goal='seek';n.target={x:supplier.x,y:supplier.y};n.goalText=`Going to ${supplier.name} for a usable Warden Blade`;}else{n.goal='gear';n.target={...n.work};n.goalText=`Needs a usable Warden Blade before answering ${dangerCall.reporter.name}'s warning`;}n.request=requestFor(n);return;}n.goal='patrol';n.target={x:dangerCall.enemy.x,y:dangerCall.enemy.y};n.goalText=`Responding to ${dangerCall.reporter.name}'s warning`;n.request=requestFor(n);return;}const hour=(world.minute/60)%24;const directNeed=topNeed(n),production=productionNeed(n),need=production&&production.score>directNeed.score?production:directNeed;n.productionPlan=need===production?{...production}:null;const night=hour>=21||hour<6;const scores={sleep:night?6+(100-n.energy)/15:(100-n.energy)/40,work:(hour>=7&&hour<18?4:0)+(n.role==='trader'?1:0),eat:n.hunger/14,seek:need.score*1.6,social:n.mood<45?2.5:0,idle:1};let goal=Object.entries(scores).sort((a,b)=>b[1]-a[1])[0][0];
    n.seekSource=null;
    if(goal==='sleep'){n.target={...n.home};n.goalText='Heading home to rest';}
    else if(goal==='work'){n.target={...n.work};n.goalText=`Working as the ${n.role}`;}
    else if(goal==='eat'){const rowan=npcs.find(x=>x.id==='rowan');n.target=rowan?{x:rowan.x,y:rowan.y}:{x:870,y:680};n.goalText='Looking for food';}
    else if(goal==='seek'){const id=need.id,supplier=supplierFor(n,id),spot=fieldSpot(id,n,!!(n.avoidEnemyId&&liveEnemy(n.avoidEnemyId))),purpose=n.productionPlan?` to make ${itemDefs[n.productionPlan.output].name}`:'';if(supplier){n.seekSource=supplier.id;n.target={x:supplier.x,y:supplier.y};n.goalText=`Going to ${supplier.name} for ${itemDefs[id].name}${purpose}`;}else if(spot){n.target=spot;n.goalText=`Sourcing ${itemDefs[id].name}${purpose}`;}else{n.target={x:870,y:680};n.goalText=`Trying to source ${itemDefs[id].name}${purpose}`;}if(n.role!=='warden'){const danger=dangerNear(n.target)||dangerOnRoute(n,n.target);if(danger){const fresh=n.blockedByDanger?.enemyId!==danger.id;n.blockedByDanger={enemyId:danger.id,itemId:id,target:{...n.target},day:world.day};n.target={...n.work};goal='avoid';n.goalText=`Holding back: wolf near ${itemDefs[id].name}`;if(fresh)memory(n,`Held back from ${itemDefs[id].name} because a wolf blocked the work.`);}}}
    else if(goal==='social'){const others=npcs.filter(o=>o!==n).sort((a,b)=>(n.relations?.[b.id]||0)-(n.relations?.[a.id]||0));const other=others[0]||n;n.target={x:other.x+25,y:other.y};n.goalText=`Checking in with ${other.name}`;}
    else{n.target={x:clamp(n.x+rand(-90,90),20,world.w-20),y:clamp(n.y+rand(-90,90),20,world.h-20)};n.goalText='Watching the day unfold';}
    n.goal=goal;n.request=requestFor(n);
  }

  function npcExchange(n,need){if(isArtifact(need.id)&&npcArtifactReady(n,need.id)){n.seekSource=null;n.productionPlan=null;n.think=0;return false;}const supplier=n.seekSource&&npcs.find(x=>x.id===n.seekSource);if(!supplier||supplier===n||n.exchangeCooldown>0||supplier.exchangeCooldown>0||dist(n,supplier)>50||(supplier.stock[need.id]||0)<1)return false;supplier.stock[need.id]--;n.stock[need.id]=isArtifact(need.id)?1:(n.stock[need.id]||0)+1;if(isArtifact(need.id)&&supplier.stockMeta?.[need.id]){n.stockMeta??={};n.stockMeta[need.id]=copy(supplier.stockMeta[need.id]);if(supplier.stock[need.id]<=0)delete supplier.stockMeta[need.id];}n.trades=(n.trades||0)+1;supplier.trades=(supplier.trades||0)+1;n.exchangeCooldown=supplier.exchangeCooldown=9;relation(n,supplier,.25);relation(supplier,n,.15);memory(n,`${supplier.name} supplied ${itemDefs[need.id].name} when it mattered.`);memory(supplier,`${n.name} came to me for ${itemDefs[need.id].name}.`);log(`${supplier.name} supplied ${n.name} with ${itemDefs[need.id].name}.`,'npc');n.request=requestFor(n);return true;}
  function npcEconomy(n){
    if(n.goal==='eat'){const rowan=npcs.find(x=>x.id==='rowan');if(rowan&&rowan!==n&&dist(n,rowan)<55&&n.exchangeCooldown<=0&&(rowan.stock.bread||0)>0){rowan.stock.bread--;n.stock.bread=(n.stock.bread||0)+1;n.exchangeCooldown=5;memory(n,`${rowan.name} shared bread when supplies were thin.`);}if((n.stock.bread||0)>0&&n.hunger>35){n.stock.bread--;n.hunger=Math.max(0,n.hunger-60);n.mood=Math.min(100,n.mood+5);}}
    if(n.goal==='seek'){const need=n.productionPlan?{id:n.productionPlan.id,score:n.productionPlan.score}:topNeed(n);if(need.score>.8&&!npcExchange(n,need)){const node=world.resources.find(r=>r.available&&r.type===need.id&&dist(n,r)<55);if(node){node.available=false;node.respawn=rand(80,140);n.stock[need.id]=(n.stock[need.id]||0)+1;if(n.routeOverride?.resourceId===node.id)n.routeOverride=null;memory(n,n.productionPlan?`Gathered ${itemDefs[need.id].name} to make ${itemDefs[n.productionPlan.output].name} for a shortage.`:`Found ${itemDefs[need.id].name} without waiting for help.`);n.request=requestFor(n);}}}
    if(n.role==='herbalist'&&n.productionCooldown<=0&&(n.stock.briarleaf||0)>=2&&(n.stock.mooncap||0)>=1){const shears=npcArtifactState(n,'shears');if(shears?.durability>0){n.stock.briarleaf-=2;n.stock.mooncap-=1;n.stock.tonic=(n.stock.tonic||0)+1;n.productionCooldown=18;const wear=Math.max(2,Math.round(5-(shears.quality-1)*1.5));shears.durability=Math.max(0,shears.durability-wear);shears.provenance.history.push(`Used by Mira to prepare Field Tonic on Day ${world.day}.`);if(shears.provenance.history.length>8)shears.provenance.history.shift();memory(n,'Prepared a Field Tonic from gathered plants.');if(shears.durability<=0){n.needBias.shears=Math.max(n.needBias.shears||0,7);memory(n,'My Herbal Shears failed while preparing medicine.');}}else n.needBias.shears=Math.max(n.needBias.shears||0,7);}
    if(n.role==='smith'&&n.productionCooldown<=0&&(n.stock.pick||0)<1&&(n.stock.iron||0)>=3&&(n.stock.wood||0)>=1){const hammer=npcArtifactState(n,'hammer');if(hammer?.durability>0){n.stock.iron-=3;n.stock.wood-=1;n.stock.pick=1;n.stockMeta??={};n.stockMeta.pick={quality:1.4,durability:100,maxDurability:100,provenance:{maker:n.name,madeDay:world.day,source:'Alden’s Forge',materialQuality:1.2,skillLevel:2,repairs:0,history:[`Forged by Alden on Day ${world.day}.`]}};n.productionCooldown=24;const wear=Math.max(3,Math.round(7-(hammer.quality-1)*2));hammer.durability=Math.max(0,hammer.durability-wear);hammer.provenance.history.push(`Used by Alden to forge an Iron Pick on Day ${world.day}.`);if(hammer.provenance.history.length>8)hammer.provenance.history.shift();memory(n,'Forged an Iron Pick for the Glen.');if(hammer.durability<=0){n.needBias.hammer=Math.max(n.needBias.hammer||0,7);memory(n,'My Forge Hammer failed while filling a tool order.');}}else n.needBias.hammer=Math.max(n.needBias.hammer||0,7);}
    if(n.role==='trader'&&n.productionCooldown<=0){n.stock.bread=(n.stock.bread||0)+1;n.productionCooldown=45;}
  }

  function npcSafety(n){if(n.goal!=='patrol')return;const call=activeDangerReport();if(!call){n.think=0;return;}const blade=npcArtifactState(n,'blade');if(!blade||blade.durability<=0){n.needBias.blade=Math.max(n.needBias.blade||0,6);n.goal='gear';n.target={...n.work};n.goalText='Cannot answer danger without a usable Warden Blade';n.request=requestFor(n);n.think=0;return;}n.target={x:call.enemy.x,y:call.enemy.y};if(dist(n,call.enemy)>55)return;call.enemy.dead=true;const wear=Math.max(4,Math.round(12-(blade.quality-1)*3));blade.durability=Math.max(0,blade.durability-wear);blade.provenance.history.push(`Used by Tamsin to clear danger for ${call.reporter.name} on Day ${world.day}.`);if(blade.provenance.history.length>8)blade.provenance.history.shift();const maker=blade.provenance.maker==='You'?'the blade you forged':`${blade.provenance.maker}'s blade`;memory(n,`Cleared a wolf that was blocking ${call.reporter.name}'s work with ${maker}.`);memory(call.reporter,`Tamsin cleared the wolf that stopped my work.`);relation(call.reporter,n,.35);relation(n,call.reporter,.2);call.reporter.blockedByDanger=null;call.reporter.think=0;if(blade.durability<=0){n.needBias.blade=Math.max(n.needBias.blade||0,6);memory(n,'My Warden Blade broke while keeping the road open.');}log(`Tamsin drove off a wolf so ${call.reporter.name} could get back to work.`,'npc');n.think=0;}
  function socialDelivery(n){if(n.goal!=='deliver'||!n.socialCommitment)return false;const commitment=n.socialCommitment,requester=npcs.find(x=>x.id===commitment.requesterId),id=commitment.itemId;if(requester&&isArtifact(id)&&npcArtifactReady(requester,id)){requester.brokeredNeed=null;n.socialCommitment=null;n.think=0;return false;}if(!requester||(n.stock?.[id]||0)<1){n.socialCommitment=null;if(requester)requester.brokeredNeed=null;n.think=0;return false;}n.target={x:requester.x,y:requester.y};if(dist(n,requester)>50)return false;n.stock[id]--;requester.stock[id]=isArtifact(id)?1:(requester.stock[id]||0)+1;if(isArtifact(id)&&n.stockMeta?.[id]){requester.stockMeta??={};requester.stockMeta[id]=copy(n.stockMeta[id]);if(n.stock[id]<=0)delete n.stockMeta[id];}n.trades=(n.trades||0)+1;requester.trades=(requester.trades||0)+1;relation(requester,n,.35);relation(n,requester,.25);requester.trust=clamp(requester.trust+.35,0,10);n.trust=clamp(n.trust+.2,0,10);memory(requester,`${n.name} kept the ${itemDefs[id].name} promise you brokered.`);memory(n,`I delivered ${itemDefs[id].name} to ${requester.name} after you connected us.`);log(`${n.name} delivered ${itemDefs[id].name} to ${requester.name} because of your introduction.`,'npc');requester.brokeredNeed=null;n.socialCommitment=null;requester.request=requestFor(requester);n.request=requestFor(n);requester.think=0;n.think=0;return true;}

  function updateNPC(n,dt){n.relations??={};n.productionCooldown=Math.max(0,(n.productionCooldown||0)-dt);n.exchangeCooldown=Math.max(0,(n.exchangeCooldown||0)-dt);n.think=(n.think||0)-dt;n.hunger=clamp(n.hunger+dt*.45,0,100);n.energy=clamp(n.energy-dt*(n.goal==='sleep'?-2.5:.18),0,100);n.mood=clamp(n.mood+dt*((n.hunger<55?1:-1)*.08),0,100);if(n.think<=0){chooseNpcGoal(n);n.think=rand(3,7);}if(n.goal==='seek'&&n.seekSource){const supplier=npcs.find(x=>x.id===n.seekSource);if(supplier)n.target={x:supplier.x,y:supplier.y};}if(n.goal==='deliver'&&n.socialCommitment){const requester=npcs.find(x=>x.id===n.socialCommitment.requesterId);if(requester)n.target={x:requester.x,y:requester.y};}if(n.goal==='patrol'){const call=activeDangerReport();if(call)n.target={x:call.enemy.x,y:call.enemy.y};else n.think=0;}const dx=n.target.x-n.x,dy=n.target.y-n.y,d=Math.hypot(dx,dy);if(d>4){const speed=n.goal==='sleep'?65:45;n.x+=dx/d*speed*dt;n.y+=dy/d*speed*dt;}socialDelivery(n);npcSafety(n);npcEconomy(n);}

  function priceFor(n,id,mode='buy'){const def=itemDefs[id],need=npcNeedScore(n,id),stock=n.stock[id]||0,trust=n.trust;let p=def.base*(1+need*.12)*(1+Math.max(0,2-stock)*.08);if(mode==='sell')p*=.62+Math.min(.18,trust*.01);else p*=1.2-Math.min(.18,trust*.01);return Math.max(1,Math.round(p));}
  function helpNPC(n){const r=n.request||requestFor(n);if(!r){toast(`${n.name} has no urgent request`);return false;}if(itemCount(r.id)<r.qty){toast(`Need ${r.qty} ${itemDefs[r.id].name}`);return false;}const q=avgQuality(r.id),artifact=isArtifact(r.id)?artifactSnapshot(r.id):null;removeItem(r.id,r.qty);n.stock[r.id]=artifact?1:(n.stock[r.id]||0)+r.qty;if(artifact){n.stockMeta??={};n.stockMeta[r.id]=artifact;n.seekSource=null;n.productionPlan=null;n.routeOverride=null;n.goal='idle';n.target={...n.work};n.think=0;}n.trust=clamp(n.trust+1+Math.max(0,q-1)*.4+(artifact?.provenance?.maker==='You'?.25:0),0,10);player.coins+=r.reward+Math.round((q-1)*3);n.lastPlayerHelp=world.day;memory(n,artifact?.provenance?.maker==='You'?`You brought the ${qualityLabel(q)} ${itemDefs[r.id].name} you made on Day ${artifact.provenance.madeDay} when it was needed.`:`You brought ${r.qty} ${itemDefs[r.id].name} when it was needed.`);skillXp('rapport',8);deriveIdentity();toast(`${n.name} remembers that help`);log(`${n.name}'s shortage eased because you brought ${itemDefs[r.id].name}.`,'npc');n.request=null;save();return true;}
  function sellToNPC(n){const need=topNeed(n);const id=need.id;if(itemCount(id)<1){toast(`You have no ${itemDefs[id].name}`);return false;}const price=priceFor(n,id,'sell'),q=avgQuality(id),artifact=isArtifact(id)?artifactSnapshot(id):null;removeItem(id,1);n.stock[id]=artifact?1:(n.stock[id]||0)+1;if(artifact){n.stockMeta??={};n.stockMeta[id]=artifact;}player.coins+=Math.round(price*q);n.trust=clamp(n.trust+.15+(artifact?.provenance?.maker==='You'?.15:0),0,10);memory(n,artifact?.provenance?.maker==='You'?`Bought the ${qualityLabel(q)} ${itemDefs[id].name} you made.`:`Bought ${itemDefs[id].name} from you.`);deriveIdentity();save();toast(`Sold ${itemDefs[id].name} for ${Math.round(price*q)}c`);return true;}
  function buyFromNPC(n){const entries=Object.entries(n.stock).filter(([id,q])=>q>0&&itemDefs[id]&&(!isArtifact(id)||itemCount(id)===0));if(!entries.length){toast(`${n.name} has nothing spare you can carry`);return false;}entries.sort((a,b)=>priceFor(n,a[0],'buy')-priceFor(n,b[0],'buy'));const [id]=entries[0],artifact=isArtifact(id)?n.stockMeta?.[id]:null,q=artifact?.quality||1+n.trust*.03;const price=Math.round(priceFor(n,id,'buy')*q);if(player.coins<price){toast(`Need ${price}c`);return false;}player.coins-=price;n.stock[id]--;addItem(id,1,q,artifact||{maker:n.name,source:`${n.name}'s stock`});if(isArtifact(id)&&n.stock[id]<=0&&n.stockMeta)delete n.stockMeta[id];save();toast(`Bought ${itemDefs[id].name} for ${price}c`);return true;}

  function townNeedState(){const out={food:0,medicine:0,metal:0,materials:0};for(const n of npcs){for(const id of Object.keys(n.needBias||{})){const score=npcNeedScore(n,id),kind=itemDefs[id]?.kind;if(kind==='food')out.food+=score;else if(kind==='medicine'||kind==='herb')out.medicine+=score;else if(kind==='ore'||kind==='tool'||kind==='weapon')out.metal+=score;else out.materials+=score;}}world.townNeeds=out;return out;}
  function dominantTownNeed(){const needs=townNeedState(),[key,value]=Object.entries(needs).sort((a,b)=>b[1]-a[1])[0];return{key,value,label:{food:'food',medicine:'medicine and herbs',metal:'metal and tools',materials:'field materials'}[key]};}
  function deriveIdentity(){const totalTrust=npcs.reduce((s,n)=>s+n.trust,0),helped=npcs.filter(n=>n.trust>=1).length,craft=player.skills.smithing.level+player.skills.herbcraft.level,field=player.skills.fieldcraft.level,guard=player.skills.guard.level;player.standing=totalTrust>=16?'Mainstay':totalTrust>=9?'Trusted':totalTrust>=4?'Known':'Unknown';const scores=[['keeping people supplied',totalTrust+helped*2],['making useful things',craft*2],['bringing back what the Glen needs',field*2],['keeping the roads safe',guard*2]];scores.sort((a,b)=>b[1]-a[1]);player.knownFor=scores[0][1]>4?scores[0][0]:'nothing yet';}

  function gather(node){if(!node.available)return false;const pick=player.inventory.pick,pickReady=player.equippedTool==='pick'&&pick?.durability>0,pickQuality=pickReady?avgQuality('pick'):1;let q=node.quality+(player.skills.fieldcraft.level-1)*.12+(world.weather==='rain'&&itemDefs[node.type].kind==='herb'?.18:0);let qty=1;if(node.type==='iron'){if(pickReady){qty+=player.skills.fieldcraft.level>=3?1:0;q+=(pickQuality-1)*.18;pick.durability=Math.max(0,pick.durability-Math.max(2,6-Math.floor(pickQuality)));}else q-=.35;}if(node.type==='wood'&&pickReady)q-=.2;addItem(node.type,qty,clamp(q,.7,3));node.available=false;node.respawn=rand(60,120);player.energy=Math.max(0,player.energy-(node.type==='iron'?(pickReady?8:12):4));skillXp('fieldcraft',node.type==='iron'?5:3);if(player.equippedTool==='pick'&&pick&&!pick.durability)toast('Iron Pick broke — Mend it before the next hard job');save();return true;}
  function craft(id){const r=recipes[id];if(!r)return false;if(player.skills[r.skill].level<r.level){toast(`${skillDefs[r.skill].name} ${r.level} required`);return false;}if(isArtifact(id)&&itemCount(id)>0){toast(`You already carry a ${itemDefs[id].name}; singular gear keeps its own history.`);return false;}if(!hasItems(r.input)){toast(`Missing materials for ${itemDefs[id].name}`);return false;}let total=0,count=0;for(const [mat,q] of Object.entries(r.input)){total+=avgQuality(mat)*q;count+=q;}const materialQuality=total/count;consume(r.input);const quality=clamp(materialQuality+(player.skills[r.skill].level-1)*.15,.8,3);const artifact=isArtifact(id)?{provenance:{maker:'You',madeDay:world.day,source:'Player-forged',materialQuality,skillLevel:player.skills[r.skill].level,repairs:0,history:[`Forged by You on Day ${world.day} from ${qualityLabel(materialQuality)} materials.`]}}:null;if(!addItem(id,1,quality,artifact))return false;skillXp(r.skill,10);if(id==='pick')player.equippedTool='pick';if(id==='blade')player.equippedWeapon='blade';deriveIdentity();save();toast(`Crafted ${qualityLabel(quality)} ${itemDefs[id].name}`);return true;}
  function drinkTonic(){if(itemCount('tonic')<1){toast('No Field Tonic');return false;}removeItem('tonic',1);player.hp=clamp(player.hp+35+player.skills.herbcraft.level*3,0,player.maxHp);save();toast('Field Tonic restored health');return true;}

  function nearestNPC(range=70){let best=null,bd=range;for(const n of npcs){const d=dist(player,n);if(d<bd){best=n;bd=d;}}return best;}
  function nearestResource(range=44){let best=null,bd=range;for(const r of world.resources){if(!r.available)continue;const d=dist(player,r);if(d<bd){best=r;bd=d;}}return best;}
  function nearestDrop(range=38){let best=null,bd=range;for(const d of world.drops){const dd=dist(player,d);if(dd<bd){best=d;bd=dd;}}return best;}
  function interact(){const n=nearestNPC();if(n){renderNearby(n,true);return true;}const r=nearestResource();if(r)return gather(r);const d=nearestDrop();if(d){addItem(d.item,1,d.quality);world.drops=world.drops.filter(x=>x!==d);save();return true;}toast('Nothing useful within reach');return false;}

  function combatProfile(){const blade=player.inventory.blade,bladeReady=player.equippedWeapon==='blade'&&blade?.durability>0,bladeQuality=bladeReady?avgQuality('blade'):1;return{bladeReady,bladeQuality,range:bladeReady?58:42,damage:bladeReady?Math.round((18+player.skills.guard.level*2)*(1+(bladeQuality-1)*.18)):9+player.skills.guard.level};}
  function attack(){if(player.attackCd>0||player.energy<4)return;player.attackCd=.38;player.attackArc=.14;player.energy-=4;const profile=combatProfile(),blade=player.inventory.blade;if(player.equippedWeapon==='blade'&&blade&&!profile.bladeReady)toast('The Warden Blade is broken — fighting without its edge');for(const e of world.enemies){if(e.dead)continue;if(dist(player,e)<=profile.range){e.hp-=profile.damage;skillXp('guard',2);if(profile.bladeReady)blade.durability=Math.max(0,blade.durability-1);if(e.hp<=0){e.dead=true;world.drops.push({x:e.x,y:e.y,item:'hide',quality:rand(1,2.2)});player.coins+=3;log('A wolf fell. Its hide may matter more to someone than the coins.','combat');}break;}}}
  function updateEnemy(e,dt){if(e.dead)return;e.attackCd=Math.max(0,e.attackCd-dt);const d=dist(player,e);if(d<230){const dx=player.x-e.x,dy=player.y-e.y,dd=Math.max(1,Math.hypot(dx,dy));e.x+=dx/dd*72*dt;e.y+=dy/dd*72*dt;if(dd<28&&e.attackCd<=0){e.attackCd=1.1;let dmg=10;if(player.guarded){dmg=1;player.guarded=false;e.hp-=6+player.skills.guard.level*2;toast('Brace held — countered');}player.hp=Math.max(0,player.hp-dmg);if(player.hp<=0){player.hp=player.maxHp;player.energy=50;player.x=900;player.y=600;player.coins=Math.max(0,player.coins-10);log('You were carried back to Briar Glen. The wilds collected their price.','combat');}}}else{e.wander-=dt;if(e.wander<=0){e.vx=rand(-1,1);e.vy=rand(-1,1);e.wander=rand(2,6);}e.x+=e.vx*18*dt;e.y+=e.vy*18*dt;}}

  function respawn(dt){for(const r of world.resources){if(r.available)continue;r.respawn-=dt;if(r.respawn<=0){r.available=true;r.quality=clamp(r.quality+rand(-.25,.25),.7,2.8);}}if(world.enemies.filter(e=>!e.dead).length<7&&Math.random()<dt*.03)spawnWolf(rand(1220,1690),rand(270,680));}
  function updateWeather(dt){world.weatherTimer-=dt;if(world.weatherTimer<=0){const old=world.weather;world.weather=Math.random()<.38?'rain':'clear';world.weatherTimer=rand(160,300);if(old!==world.weather)log(world.weather==='rain'?'Rain settles over Briar Glen. Herbs will come up richer.':'The rain clears. Roads dry and travel quickens.','world');}}
  function updateClock(dt){world.minute+=dt*5.2;if(world.minute>=1440){world.minute-=1440;world.day++;log(`Day ${world.day} begins. Prices and shortages have shifted.`,'world');for(const n of npcs)n.trust=clamp(n.trust-.03,0,10);}world.minute=Math.max(0,world.minute);}

  const keys=new Set();
  addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='Space')attack();if(e.code==='KeyE')interact();if(e.code==='Digit1')useSkill('fieldcraft');if(e.code==='Digit2')useSkill('smithing');if(e.code==='Digit3')useSkill('guard');if(e.code==='Digit4')useSkill('rapport');if(e.code==='KeyQ')drinkTonic();});
  addEventListener('keyup',e=>keys.delete(e.code));
  document.getElementById('attack-btn').addEventListener('click',attack);document.getElementById('interact-btn').addEventListener('click',interact);document.getElementById('clear-log').addEventListener('click',()=>{world.events=[];renderLog();});
  for(const b of document.querySelectorAll('[data-move]')){const code={up:'ArrowUp',down:'ArrowDown',left:'ArrowLeft',right:'ArrowRight'}[b.dataset.move];const on=()=>keys.add(code),off=()=>keys.delete(code);b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off);}

  function updatePlayer(dt){let dx=0,dy=0;if(keys.has('KeyW')||keys.has('ArrowUp'))dy--;if(keys.has('KeyS')||keys.has('ArrowDown'))dy++;if(keys.has('KeyA')||keys.has('ArrowLeft'))dx--;if(keys.has('KeyD')||keys.has('ArrowRight'))dx++;if(dx||dy){const len=Math.hypot(dx,dy);let speed=player.speed*(world.weather==='rain'?.93:1);if(inventoryWeight()>18)speed*=.78;player.x=clamp(player.x+dx/len*speed*dt,18,world.w-18);player.y=clamp(player.y+dy/len*speed*dt,18,world.h-18);player.energy=Math.max(0,player.energy-dt*.7);}else player.energy=Math.min(player.maxEnergy,player.energy+dt*2.2);player.attackCd=Math.max(0,player.attackCd-dt);player.attackArc=Math.max(0,player.attackArc-dt);}

  function update(dt){updatePlayer(dt);updateClock(dt);updateWeather(dt);for(const n of npcs)updateNPC(n,dt);for(const e of world.enemies)updateEnemy(e,dt);respawn(dt);deriveIdentity();}

  function worldToScreen(x,y){return{x:x-camera.x,y:y-camera.y};}
  function drawGround(){ctx.fillStyle=world.weather==='rain'?'#27332d':'#2d3a2c';ctx.fillRect(0,0,canvas.width,canvas.height);for(const z of zones){const p=worldToScreen(z.x,z.y);ctx.fillStyle=z.color;ctx.globalAlpha=.58;ctx.fillRect(p.x,p.y,z.w,z.h);ctx.globalAlpha=1;ctx.fillStyle='rgba(240,239,228,.65)';ctx.font='12px system-ui';ctx.fillText(z.name,p.x+10,p.y+18);}if(world.weather==='rain'){ctx.strokeStyle='rgba(184,208,220,.22)';ctx.lineWidth=1;for(let i=0;i<80;i++){const x=(i*83+performance.now()*.12)%canvas.width,y=(i*47+performance.now()*.22)%canvas.height;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-4,y+10);ctx.stroke();}}}
  function drawBuildings(){for(const b of buildings){const p=worldToScreen(b.x,b.y);ctx.fillStyle=b.color;ctx.fillRect(p.x,p.y,b.w,b.h);ctx.strokeStyle='rgba(0,0,0,.35)';ctx.strokeRect(p.x,p.y,b.w,b.h);ctx.fillStyle='#f0efe4';ctx.font='11px system-ui';ctx.fillText(b.name,p.x+7,p.y+16);}}
  function drawResources(){const survey=performance.now()<player.surveyUntil;for(const r of world.resources){if(!r.available)continue;const p=worldToScreen(r.x,r.y);if(p.x<-20||p.y<-20||p.x>canvas.width+20||p.y>canvas.height+20)continue;ctx.fillStyle=itemDefs[r.type].color;ctx.beginPath();ctx.arc(p.x,p.y,r.r,0,TAU);ctx.fill();if(survey){ctx.strokeStyle=r.quality>=2?'#f3df88':'rgba(255,255,255,.55)';ctx.lineWidth=r.quality>=2?3:1;ctx.beginPath();ctx.arc(p.x,p.y,r.r+5,0,TAU);ctx.stroke();ctx.fillStyle='#fff';ctx.font='10px system-ui';ctx.fillText(`${qualityLabel(r.quality)} ${itemDefs[r.type].name}`,p.x+12,p.y-10);}}}
  function drawNPCs(){for(const n of npcs){const p=worldToScreen(n.x,n.y);ctx.fillStyle=n.color;ctx.beginPath();ctx.arc(p.x,p.y,n.r,0,TAU);ctx.fill();ctx.fillStyle='#fff';ctx.font='11px system-ui';ctx.fillText(n.name,p.x-18,p.y-17);if(n.request){ctx.fillStyle='#efc96f';ctx.fillText('!',p.x-2,p.y+4);}if(performance.now()<player.readNeedUntil&&dist(player,n)<240){ctx.fillStyle='rgba(14,17,13,.86)';ctx.fillRect(p.x-55,p.y+18,110,28);ctx.fillStyle='#fff';ctx.font='10px system-ui';ctx.fillText(npcNeedText(n).slice(0,25),p.x-50,p.y+35);}}}
  function drawEnemies(){for(const e of world.enemies){if(e.dead)continue;const p=worldToScreen(e.x,e.y);ctx.fillStyle='#8b6b5d';ctx.beginPath();ctx.arc(p.x,p.y,e.r,0,TAU);ctx.fill();if(e.hp<e.maxHp){ctx.fillStyle='#1b1614';ctx.fillRect(p.x-15,p.y-20,30,4);ctx.fillStyle='#d57a6f';ctx.fillRect(p.x-15,p.y-20,30*(e.hp/e.maxHp),4);}}for(const d of world.drops){const p=worldToScreen(d.x,d.y);ctx.fillStyle=itemDefs[d.item].color;ctx.fillRect(p.x-5,p.y-5,10,10);}}
  function drawPlayer(){const p=worldToScreen(player.x,player.y);ctx.fillStyle='#f0efe4';ctx.beginPath();ctx.arc(p.x,p.y,player.r,0,TAU);ctx.fill();ctx.strokeStyle=player.guarded?'#c7d77b':'#263025';ctx.lineWidth=player.guarded?4:2;ctx.stroke();if(player.attackArc>0){ctx.strokeStyle='#f4e3af';ctx.lineWidth=4;ctx.beginPath();ctx.arc(p.x,p.y,player.equippedWeapon==='blade'?58:42,-.6,.6);ctx.stroke();}}
  function draw(){camera.x=clamp(player.x-canvas.width/2,0,world.w-canvas.width);camera.y=clamp(player.y-canvas.height/2,0,world.h-canvas.height);drawGround();drawBuildings();drawResources();drawNPCs();drawEnemies();drawPlayer();const z=zoneAt(player.x,player.y);ctx.fillStyle='rgba(0,0,0,.46)';ctx.fillRect(10,10,210,42);ctx.fillStyle='#fff';ctx.font='bold 13px system-ui';ctx.fillText(z?.name||'Open Country',20,27);ctx.font='11px system-ui';ctx.fillStyle='#cfd7c8';ctx.fillText(world.weather==='rain'?'Rain · wet roads':'Clear · fair roads',20,44);}

  function renderSkills(){UI.skills.innerHTML=Object.entries(skillDefs).filter(([,d])=>d.key).map(([id,d])=>{const s=player.skills[id];return`<div class="skill"><button data-skill="${id}">${d.key}</button><div><strong>${d.active}</strong><small>${d.desc}</small></div><span class="lvl">${d.name} ${s.level}</span></div>`}).join('');for(const b of UI.skills.querySelectorAll('[data-skill]'))b.addEventListener('click',()=>useSkill(b.dataset.skill));}
  function renderInventory(){const rows=Object.entries(player.inventory).sort((a,b)=>itemDefs[a[0]].name.localeCompare(itemDefs[b[0]].name));UI.inventory.innerHTML=rows.length?rows.map(([id,s])=>{const q=s.qualitySum/s.qty,equip=player.equippedTool===id||player.equippedWeapon===id?' · equipped':'',artifact=isArtifact(id)?normalizeArtifactSlot(id,s):null,dur=artifact?` · ${Math.round(artifact.durability)}/${Math.round(artifact.maxDurability)}`:'';const story=artifact?` · ${artifact.provenance.maker} D${artifact.provenance.madeDay} · repaired ${artifact.provenance.repairs}×`:'';return`<div class="item-row"><b>${itemDefs[id].name}${equip}</b><span class="q">${qualityLabel(q)}${dur}${story}</span><span>×${s.qty}</span></div>`}).join(''):'Your pack is empty.';UI.packWeight.textContent=`${inventoryWeight().toFixed(1)} / 22 weight`;}
  function renderNearby(n=nearestNPC(85),force=false){const r=nearestResource(48),d=nearestDrop(42);if(n){UI.nearbyType.textContent=n.role;const req=n.request||requestFor(n);const remember=n.memory.at(-1)?.text||'No history with you yet.',workToolId=professionTools[n.role],workTool=workToolId?npcArtifactState(n,workToolId):null,damaged=damagedArtifactForNpc(n),gear=workTool?`<div>${itemDefs[workToolId].name} · ${workTool.provenance.maker} · ${Math.round(workTool.durability)}/${Math.round(workTool.maxDurability)}${damaged?.id===workToolId?' · Smithing can service':''}</div>`:damaged?`<div>${itemDefs[damaged.id].name} · ${Math.round(damaged.meta.durability)}/${Math.round(damaged.meta.maxDurability)} · Smithing can service</div>`:'';UI.nearby.innerHTML=`<b>${n.name}</b> · trust ${n.trust.toFixed(1)}<br>${n.goalText}${gear}<div class="need">${performance.now()<player.readNeedUntil||force?npcNeedText(n):'Use Read Need (4) to understand priorities.'}</div><small>${remember}</small><div>${req?`Request: ${req.qty} ${itemDefs[req.id].name} · ${req.reward}c`: 'No urgent request.'}</div><button data-near="help" ${req&&itemCount(req.id)>=req.qty?'':'disabled'}>Help</button><button data-near="sell">Sell need</button><button data-near="buy">Buy spare</button>`;UI.nearby.querySelector('[data-near=help]')?.addEventListener('click',()=>helpNPC(n));UI.nearby.querySelector('[data-near=sell]')?.addEventListener('click',()=>sellToNPC(n));UI.nearby.querySelector('[data-near=buy]')?.addEventListener('click',()=>buyFromNPC(n));return;}if(r){UI.nearbyType.textContent='resource';UI.nearby.innerHTML=`<b>${itemDefs[r.type].name}</b><br>${performance.now()<player.surveyUntil?`${qualityLabel(r.quality)} quality · `:''}Use E to gather.`;return;}if(d){UI.nearbyType.textContent='drop';UI.nearby.innerHTML=`<b>${itemDefs[d.item].name}</b><br>Use E to pick it up.`;return;}UI.nearbyType.textContent='';UI.nearby.textContent='Walk up to someone or something useful.';}
  function renderLog(){UI.log.innerHTML=world.events.slice(-18).map(e=>`<div class="log-entry ${e.type}"><b>D${e.day}</b> ${e.text}</div>`).join('');}
  function renderUI(){const h=Math.floor(world.minute/60)%24,m=Math.floor(world.minute%60);UI.clock.textContent=`Day ${world.day} · ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;UI.coins.textContent=`${player.coins}c`;UI.hp.value=player.hp;UI.energy.value=player.energy;UI.standing.textContent=player.standing;UI.knownFor.textContent=`Known for: ${player.knownFor}`;const need=dominantTownNeed(),blocked=npcs.find(n=>n.blockedByDanger&&liveEnemy(n.blockedByDanger.enemyId));UI.worldLine.textContent=blocked?`${blocked.name}'s work is stalled by danger. Tamsin is reacting.`:world.weather==='rain'?`Rain enriches the fields. Briar Glen is watching ${need.label}.`:need.value>2?`Briar Glen is short on ${need.label}. People are already reacting.`:'Briar Glen is supplied for now. People are pursuing their own work.';renderSkills();renderInventory();renderNearby();}

  function save(){try{localStorage.setItem(BUILD.saveKey,JSON.stringify({build:BUILD.version,world:{minute:world.minute,day:world.day,weather:world.weather,weatherTimer:world.weatherTimer,events:world.events,resources:world.resources,enemies:world.enemies,drops:world.drops,serial:world.serial},player:{...player},npcs}));}catch(_){}}
  function load(){try{const raw=localStorage.getItem(BUILD.saveKey);if(!raw)return false;const s=JSON.parse(raw);if(!s?.player||!s?.world||!Array.isArray(s.npcs))return false;Object.assign(world,s.world);Object.assign(player,s.player);npcs=s.npcs;for(const [id,slot] of Object.entries(player.inventory||{}))if(isArtifact(id))normalizeArtifactSlot(id,slot);for(const n of npcs){n.stockMeta=n.stockMeta&&typeof n.stockMeta==='object'?n.stockMeta:{};for(const id of Object.keys(n.stockMeta))if(isArtifact(id)&&(n.stock?.[id]||0)>0)npcArtifactState(n,id);n.socialCommitment=n.socialCommitment&&typeof n.socialCommitment==='object'?n.socialCommitment:null;n.brokeredNeed=n.brokeredNeed&&typeof n.brokeredNeed==='object'?n.brokeredNeed:null;}return true;}catch(_){return false;}}

  let last=performance.now(),uiTimer=0,saveTimer=0;
  function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);draw();uiTimer-=dt;saveTimer-=dt;if(uiTimer<=0){renderUI();uiTimer=.18;}if(saveTimer<=0){save();saveTimer=5;}requestAnimationFrame(frame);}

  window.__BRIAR_GLEN_DEBUG__={
    build:()=>({...BUILD}),snapshot:()=>({day:world.day,minute:world.minute,weather:world.weather,townNeeds:{...townNeedState()},player:JSON.parse(JSON.stringify(player)),npcs:JSON.parse(JSON.stringify(npcs)),resources:world.resources.filter(r=>r.available).length,enemies:world.enemies.filter(e=>!e.dead).length}),
    reset:()=>{localStorage.removeItem(BUILD.saveKey);reset();renderUI();},
    give:(id,qty=1,quality=1)=>{addItem(id,qty,quality);renderUI();save();return itemCount(id);},
    setPosition:(x,y)=>{player.x=x;player.y=y;return{x:player.x,y:player.y};},
    npc:(id)=>npcs.find(n=>n.id===id)||null,
    forceNpcNeed:(npcId,itemId)=>{const n=npcs.find(x=>x.id===npcId);if(!n||!itemDefs[itemId])return false;const otherMax=Math.max(0,...Object.keys(n.needBias||{}).filter(id=>id!==itemId).map(id=>npcNeedScore(n,id)));n.stock[itemId]=0;const deficit=isArtifact(itemId)?1:3;n.needBias[itemId]=(otherMax+10)/deficit;chooseNpcGoal(n);renderNearby(n,true);return true;},
    setNpcStock:(npcId,itemId,qty)=>{const n=npcs.find(x=>x.id===npcId);if(!n||!itemDefs[itemId])return false;n.stock[itemId]=Math.max(0,Number(qty)||0);if(isArtifact(itemId)&&n.stock[itemId]<=0&&n.stockMeta)delete n.stockMeta[itemId];return true;},
    npcArtifact:(npcId,itemId)=>{const n=npcs.find(x=>x.id===npcId);return n?npcArtifactSnapshot(n,itemId):null;},
    setNpcArtifactDurability:(npcId,itemId,value)=>{const n=npcs.find(x=>x.id===npcId);if(!n)return false;const meta=npcArtifactState(n,itemId);if(!meta)return false;meta.durability=clamp(Number(value)||0,0,meta.maxDurability);return meta.durability;},
    setSkillLevel:(id,level)=>{if(!player.skills[id])return false;player.skills[id].level=clamp(Math.round(Number(level)||1),1,5);player.skills[id].xp=0;return player.skills[id].level;},
    clearEnemies:()=>{world.enemies=[];return true;},
    spawnWolfAt:(x,y)=>{spawnWolf(Number(x)||0,Number(y)||0);return world.enemies.at(-1)?.id||null;},
    enemy:(id)=>world.enemies.find(e=>e.id===id)||null,
    rethink:(npcId)=>{const n=npcs.find(x=>x.id===npcId);if(!n)return false;chooseNpcGoal(n);return n.goal;},
    setDurability:(id,value)=>{const slot=player.inventory[id];if(!slot||slot.durability==null)return false;normalizeArtifactSlot(id,slot);slot.durability=clamp(Number(value)||0,0,slot.maxDurability);return slot.durability;},
    artifact:(id)=>artifactSnapshot(id),
    equip:(id)=>{if(!player.inventory[id])return false;if(itemDefs[id].kind==='tool')player.equippedTool=id;if(itemDefs[id].kind==='weapon')player.equippedWeapon=id;return true;},
    combatProfile:()=>({...combatProfile()}),
    advance:(seconds=1)=>{const steps=Math.max(1,Math.ceil(seconds/.1)),dt=seconds/steps;for(let i=0;i<steps;i++)update(dt);renderUI();save();return window.__BRIAR_GLEN_DEBUG__.snapshot();},
    help:(npcId)=>{const n=npcs.find(x=>x.id===npcId);return n?helpNPC(n):false;},
    craft,
    useSkill,
    attack,
    save,
  };

  document.addEventListener('click',e=>{const target=e.target.closest?.('[data-craft]');if(target)craft(target.dataset.craft);});
  const craftBox=document.createElement('section');craftBox.className='card';craftBox.innerHTML='<div class="card-title"><span>Make</span><small>items exist to solve problems</small></div><div class="nearby"><button data-craft="tonic">Brew Tonic</button><button data-craft="pick">Forge Pick</button><button data-craft="blade">Forge Blade</button><button id="drink-tonic">Drink Tonic (Q)</button></div>';document.querySelector('.sidebar').insertBefore(craftBox,document.querySelector('.log-card'));document.getElementById('drink-tonic').addEventListener('click',drinkTonic);

  if(!load())reset();deriveIdentity();renderLog();renderUI();requestAnimationFrame(frame);
})();
